### ISSUE TITLE
Trigger a plan for a different workspaces after an apply

### ISSUE THREAD

**Issue by adampie** [zapier/tfbuddy#42]
We have a use case where a resource is created in one workspace but another workspace manages access to said resource. 

Having tfbuddy automatically run a plan on the second workspace after a successful apply to the first would be ideal.

```yaml
workspaces:
  - name: a_prod
    dir: prod
    triggerDirs:
      - prod/**
    triggerWorkspacePostApply:
      - a_shared

  - name: a_shared
    dir: shared
    triggerDirs:
      - shared/** 
```
